services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: ha-dev
    ports:
      - "8123:8123"
    volumes:
      - ./config:/config
      - ./custom_components:/config/custom_components
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Brussels
    restart: unless-stopped
